export const PROJECTNAME = 'ARMAXVIEW';
export const MODULENAME = 'DATASCRAPPER';
export const SUBAPPNAME = 'RAWDATA';
export const APPNAME = `${PROJECTNAME}_${MODULENAME}_${SUBAPPNAME}`;
export const BLOCK_TRANSFER_STATUS = 'BLOCKTRANSFERSTATUS';
