export const PROJECTNAME = 'ARMAXVIEW';
export const MODULENAME = 'DATASCRAPPER';
export const SUBAPPNAME = 'NOTIFICATIONENGINE';
export const APPNAME = `${PROJECTNAME}_${MODULENAME}_${SUBAPPNAME}`;
