export const PROJECTNAME = 'ARMAXVIEW';
export const MODULENAME = 'DATASCRAPPER';
export const PROTOCOL_CHANNEL = 'PROTOCOL_CHANNEL';
export const DATA_CHANNEL = 'DATA_CHANNEL';
export const EXIT_CHANNEL = 'EXIT_CHANNEL';
export const LATESTVERSIONID = 'LATESTVERSIONID';
