export const PROJECTNAME = 'ARMAXVIEW';
export const MODULENAME = 'DATASCRAPPER';
export const SUBAPPNAME = 'CRON';
export const APPNAME = `${PROJECTNAME}_${MODULENAME}_${SUBAPPNAME}`;
export const LATESTVERSION = 'LATESTVERSION';
